### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by umairnsr87** [divyanshub024/ChatBot#4]
i am unable to find the modules after opening this repo

**Comment by divyanshub024** [comment]
@umairnsr87 There is only one module "app".

**Comment by umairnsr87** [comment]
it is showing:
00:34	Unsupported Modules Detected: Compilation is not supported for following modules: ChatBot1. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

00:34	Gradle sync started

00:34	Error Loading Project: Cannot load 2 modules Details...

**Comment by divyanshub024** [comment]
Go to File -> Invalidate Caches / Restart -> Invalidate Caches & Restart.
Then try to build the application again.
